### PR TITLE
Disable quote changes in JSON

### PR DESCRIPTION
**Pull request by colinta**

### CODE REVIEW

**Comment by colinta** [comment]
If anyone wants to take a quick peek, to make sure I didn't miss a comma (or use the wrong quote! haha).

I verified locally that this works as expected (disables quote changes in `source.json`).

**Comment by pepkin88** [comment]
Looks correct.

**Comment by LeonardoGentile** [comment]
@colinta @pepkin88 I've upgraded the package but this is still happening. 
To prevent this to happen I have to set this block in my custom user settings 
```
 "source.json": {
      "quotes": [["\""]]
    },
```
Although I can see that you added this to the default settings it seems to still produce the problem unless I also add it to the custom User settings.

**Comment by colinta** [comment]
Yeah if you have custom user settings they overwrite (not complement) the default settings.

**Comment by LeonardoGentile** [comment]
Ahh I see 👍

**Pull request merged**
